-- Backfill IPA on PRODUCTION, matched by phrase text (portable across DBs).
-- Generated from local DB. Only fills rows whose ipa is currently empty.
-- Run once in the production Supabase SQL Editor.

update public.phrases set ipa = '/ə ˌpiːs əv ˈwɜːk/' where phrase = 'A piece of work' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɐkˈɔːdɪŋli/' where phrase = 'Accordingly' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈeɪs ˌʌp wˈɒnz slˈiːv/' where phrase = 'Ace up one''s sleeve' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɐknˈɒlɪdʒ ɹɪsˈiːt/' where phrase = 'Acknowledge receipt' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈakʃən ˈaɪtəm/' where phrase = 'Action item' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈæk.ʃə.nə.bəl/' where phrase = 'Actionable' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/əˈdʒɪl.ə.ti/' where phrase = 'Agility' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɐɡɹˈiː tə dˌɪsɐɡɹˈiː/' where phrase = 'Agree to disagree' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '[əˈɫaɪnmənt]' where phrase = 'Alignment' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌaləkˈeɪʃən/' where phrase = 'Allocation' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɐpˈɒlədʒiz fəðə dɪlˈeɪ/' where phrase = 'Apologies for the delay' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɐpɹˈiːʃɪˌeɪt jɔː pˈeɪʃəns/' where phrase = 'Appreciate your patience' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/az pɜːɹ ˌaʊə dɪskˈʌʃən/' where phrase = 'As per our discussion' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌeɪˌɛsˌeɪpˈiː/' where phrase = 'ASAP' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/at jɔːɹ ˈɜːlɪɪst kənvˈiːnɪəns/' where phrase = 'At your earliest convenience' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɐtˈatʃt plˈiːz fˈaɪnd/' where phrase = 'Attached please find' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '[əˈtɹɪʃən]' where phrase = 'Attrition' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈak bˈɜːnə/' where phrase = 'Back burner' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈak tə skwˈeə wˌɒn/' where phrase = 'Back to square one' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈak tə ðə dɹˈɔːɪŋ bˈɔːd/' where phrase = 'Back to the drawing board' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈbæk.lɒɡ/' where phrase = 'Backlog' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈbændwɪdθ/' where phrase = 'Bandwidth' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈɑːɡɪnɪŋ tʃˈɪp/' where phrase = 'Bargaining chip' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈeə wɪð mˌiː/' where phrase = 'Bear with me' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈiːt ðə klˈɒk/' where phrase = 'Beat the clock' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈɛntʃmɑːk/' where phrase = 'Benchmark' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bɪˈsaɪd ðə pɔɪnt/' where phrase = 'Beside the point' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈɛst pɹˈaktɪs/' where phrase = 'Best practice' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈɛst ɹɪɡˈɑːdz/' where phrase = 'Best regards' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈbetə get ˈgəʊɪŋ/' where phrase = 'Better get going' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈaɪd wˈɒnz tˈaɪm/' where phrase = 'Bide one''s time' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈaɪt ˈɒf mˈɔː ðɐn juː kan tʃˈuː/' where phrase = 'Bite off more than you can chew' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈaɪt ðə bˈʊlɪt/' where phrase = 'Bite the bullet' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/blˈəʊ ˈɒf stˈiːm/' where phrase = 'Blow off steam' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈɔɪl ðɪ ˈəʊʃən/' where phrase = 'Boil the ocean' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈɒtəlnˌɛk/' where phrase = 'Bottleneck' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈɒtəm lˈaɪn/' where phrase = 'Bottom line' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bɹˈeɪnstɔːmɪŋ/' where phrase = 'Brainstorming' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bɹˈas tˈaks/' where phrase = 'Brass tacks' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈbɹeɪk ði ˈaɪs/' where phrase = 'Break the ice' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bɹˈɪdʒ ðə ɡˈap/' where phrase = 'Bridge the gap' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bɹˈɪŋ ˈaʊt ðə bˈɛst/' where phrase = 'Bring out the best' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bɹˈɪŋ tə ðə tˈeɪbəl/' where phrase = 'Bring to the table' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bɹˈɪŋ ˈʌp/' where phrase = 'Bring up' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈɜːn ɹˈeɪt/' where phrase = 'Burn rate' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈaɪ tˈaɪm/' where phrase = 'Buy time' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/bˈaɪˈɪn/' where phrase = 'Buy-in' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/baɪ ðə bˈʊk/' where phrase = 'By the book' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/baɪ wˈɜːd ɒv mˈaʊθ/' where phrase = 'By word of mouth' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɔːl ɪt ɐ dˈeɪ/' where phrase = 'Call it a day' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɔːl ɪt ɐ nˈaɪt/' where phrase = 'Call it a night' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɔːl ˈaʊt/' where phrase = 'Call out' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɔːl ðə blˈʌf/' where phrase = 'Call the bluff' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɔːl ðə ʃˈɒts/' where phrase = 'Call the shots' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kəˈpæsɪti/' where phrase = 'Capacity' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈatʃ juː lˈeɪtə/' where phrase = 'Catch you later' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈeɪv ˈɪn/' where phrase = 'Cave in' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˌiːsˈiː slˈaʃ bˌiːsˌiːsˈiː/' where phrase = 'CC / BCC' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tʃˈeɪndʒ mˈanɪdʒmənt/' where phrase = 'Change management' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈɜːkəl bˈak/' where phrase = 'Circle back' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈɜːklɪŋ bˈak/' where phrase = 'Circling back' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/klˈaɹɪfˌaɪ/' where phrase = 'Clarify' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/klˈiə ðɪ ˈeə/' where phrase = 'Clear the air' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/klˈəʊs ɐ dˈiːl/' where phrase = 'Close a deal' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈəʊld ʃˈəʊldə/' where phrase = 'Cold shoulder' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɒmən ɡɹˈaʊnd/' where phrase = 'Common ground' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɒnfɪdənt ðˈat/' where phrase = 'Confident that' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kənsˈɛnsəs/' where phrase = 'Consensus' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kəntˈɪndʒənsi plˈan/' where phrase = 'Contingency plan' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɔː kˈɒmpɪtənsi/' where phrase = 'Core competency' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɔːnə ðə mˈɑːkɪt/' where phrase = 'Corner the market' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɔːpəɹət lˈadə/' where phrase = 'Corporate ladder' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɒst ɐn ˈɑːm and ɐ lˈɛɡ/' where phrase = 'Cost an arm and a leg' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈaʊntəɹˈɒfə/' where phrase = 'Counter-offer' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kɹˈɒs ðat bɹˈɪdʒ wɛn juː kˈʌm tʊ ɪt/' where phrase = 'Cross that bridge when you come to it' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kɹˈɒsfˈʌŋkʃənəl/' where phrase = 'Cross-functional' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kɹˈʌntʃ tˈaɪm/' where phrase = 'Crunch time' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kɹˈaɪ ˌəʊvə spˈɪld mˈɪlk/' where phrase = 'Cry over spilled milk' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈʌt kˈɔːnəz/' where phrase = 'Cut corners' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈʌt tə ðə tʃˈeɪs/' where phrase = 'Cut to the chase' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dˈɛdlɒk/' where phrase = 'Deadlock' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dˈiːlbɹeɪkə/' where phrase = 'Dealbreaker' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dˈiːp dˈaɪv/' where phrase = 'Deep dive' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dˈɛlɪɡˌeɪt/' where phrase = 'Delegate' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dɪˈlɪvɹəbəɫ/' where phrase = 'Deliverable' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dɪˈplɔɪ/' where phrase = 'Deploy' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dˈɛvəlz ˈadvəkˌeɪt/' where phrase = 'Devil''s advocate' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dˈɪdnt mˈiːn tuː/' where phrase = 'Didn''t mean to' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dˌaʊn tʊ ˈɜːθ/' where phrase = 'Down to earth' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dˈaʊntaɪm/' where phrase = 'Downtime' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dɹˈɔː ðə lˈaɪn/' where phrase = 'Draw the line' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dɹˈɪl dˈaʊn/' where phrase = 'Drill down' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dɹˈaɪv ɐ hˈɑːd bˈɑːɡɪn/' where phrase = 'Drive a hard bargain' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈɜːlɪɪst kənvˈiːnɪəns/' where phrase = 'Earliest convenience' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈɛlɪfənt ɪnðə ɹˈuːm/' where phrase = 'Elephant in the room' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈɛləveɪtə ˈpɪtʃ/' where phrase = 'Elevator pitch' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɛmpˈaʊə/' where phrase = 'Empower' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɛŋklˈəʊzd/' where phrase = 'Enclosed' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈaʊd slˈaʃ kˈɒb/' where phrase = 'EOD / COB' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈɛkspədˌaɪt/' where phrase = 'Expedite' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈeɪs ðə mjˈuːzɪk/' where phrase = 'Face the music' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈeɪs ðə mjˈuːzɪk/' where phrase = 'Face the music' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈeəɹ ɪnˈʌf/' where phrase = 'Fair enough' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈasttɹˈak/' where phrase = 'Fast-track' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈaɪnd jɔː fˈiːt/' where phrase = 'Find your feet' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈfɪt æz ə ˈfɪdl̩/' where phrase = 'Fit as a fiddle' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈɒləʊɪŋ ˈʌp/' where phrase = 'Following up' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈʊt ɪnðə dˈɔː/' where phrase = 'Foot in the door' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fɔː ɹˈiəl/' where phrase = 'For real' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈɔːs sˈʌmwɒnz hˈand/' where phrase = 'Force someone''s hand' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈɜːðə tʊ ˌaʊə kɒnvəsˈeɪʃən/' where phrase = 'Further to our conversation' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌɛfwˌaɪˈaɪ/' where phrase = 'FYI' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˈeɪm tʃˈeɪndʒə/' where phrase = 'Game changer' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡɛt ɐhˈɛd ɒvðə kˈɜːv/' where phrase = 'Get ahead of the curve' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡɛt dˌaʊn tə bˈɪznəs/' where phrase = 'Get down to business' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡɛt ˈɒf ðə ɡɹˈaʊnd/' where phrase = 'Get off the ground' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡɛt ˌaʊtəv hˈand/' where phrase = 'Get out of hand' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡɛt ðə bˈɔːl ɹˈəʊlɪŋ/' where phrase = 'Get the ball rolling' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡɛt tə ðə bˈɒtəm ɒv/' where phrase = 'Get to the bottom of' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡɛt ˌʌp tə spˈiːd/' where phrase = 'Get up to speed' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˈɪv mˌiː ɐ bɹˈeɪk/' where phrase = 'Give me a break' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˈɪv mˌiː ɐ hˈand/' where phrase = 'Give me a hand' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˌəʊ əbˌʌv and bɪjˈɒnd/' where phrase = 'Go above and beyond' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˌəʊ ˈəʊvə/' where phrase = 'Go over' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˌəʊ ðɪ ˈɛkstɹə mˈaɪl/' where phrase = 'Go the extra mile' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˌəʊ wɪððə flˈəʊ/' where phrase = 'Go with the flow' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˌəʊlˈaɪv/' where phrase = 'Go-live' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡˈʊd fɔː juː/' where phrase = 'Good for you' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɡɹˈiːn lˈaɪt/' where phrase = 'Green light' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈaɡlɪŋ/' where phrase = 'Haggling' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈaŋ ˌɒn ɐ sˈɛkənd/' where phrase = 'Hang on a second' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈɑːd skˈɪlz/' where phrase = 'Hard skills' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈɑːdbɔːl/' where phrase = 'Hardball' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈɛdkaʊnt/' where phrase = 'Headcount' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈɜːdɪŋ kˈats/' where phrase = 'Herding cats' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hiəwˈɪð/' where phrase = 'Herewith' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈaɪ stˈeɪks/' where phrase = 'High stakes' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈɪt ɐ snˈaɡ/' where phrase = 'Hit a snag' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈɪt ðə bˈʊks/' where phrase = 'Hit the books' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈɪt ðə sˈak/' where phrase = 'Hit the sack' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈəʊld ˈɔːl ðə kˈɑːdz/' where phrase = 'Hold all the cards' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈəʊld jɔː ɡɹˈaʊnd/' where phrase = 'Hold your ground' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/hˈəʊld jɔː hˈɔːsɪz/' where phrase = 'Hold your horses' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪ kˈɑːnt bɪlˈiːv ɪt/' where phrase = 'I can''t believe it' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪ hav nˈəʊ klˈuː/' where phrase = 'I have no clue' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪ hav nˈəʊ aɪdˈiə/' where phrase = 'I have no idea' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪ hˈiə juː/' where phrase = 'I hear you' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪ nˈəʊ ɹˈaɪt/' where phrase = 'I know, right?' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪ mˈiːn ɪt/' where phrase = 'I mean it' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪd lˈaɪk tə pɹəpˈəʊz/' where phrase = 'I''d like to propose' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪd lˈʌv tuː/' where phrase = 'I''d love to' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪd ɹˈɑːðə nˈɒt/' where phrase = 'I''d rather not' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪl sˈiː wɒt aɪ kan dˈuː/' where phrase = 'I''ll see what I can do' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪl tˈeɪk ɪt/' where phrase = 'I''ll take it' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪm ˈɔːl ˈiəz/' where phrase = 'I''m all ears' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪm ˈɔːl sˈɛt/' where phrase = 'I''m all set' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪm dˌaʊn fɔː ðˈat/' where phrase = 'I''m down for that' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪm ɡˈʊd/' where phrase = 'I''m good' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪm nˌɒt ʃˈʊə/' where phrase = 'I''m not sure' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪm tˈɛlɪŋ juː/' where phrase = 'I''m telling you' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/aɪm wˈɜːkɪŋ ˈɒn ɪt/' where phrase = 'I''m working on it' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈɪɡnəɹəns ɪz blˈɪs/' where phrase = 'Ignorance is bliss' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪn lˈaɪt ɒv/' where phrase = 'In light of' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪn ɹɪspˈɒns tuː/' where phrase = 'In response to' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪnðə blˈɪŋk əvən ˈaɪ/' where phrase = 'In the blink of an eye' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪnðə lˈɒŋ ɹˈʌn/' where phrase = 'In the long run' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪnðə pˈaɪplaɪn/' where phrase = 'In the pipeline' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪnðə ɹˈɛd/' where phrase = 'In the red' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪnðə wˈiːdz/' where phrase = 'In the weeds' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪŋkənvˈiːnɪəns kˈɔːzd/' where phrase = 'Inconvenience caused' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪŋkwˈaɪəɹ ɐbˈaʊt/' where phrase = 'Inquire about' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈaɪən ˈaʊt/' where phrase = 'Iron out' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪt ɪz wɒt ɪt ˈɪz/' where phrase = 'It is what it is' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɪts nˌɒtə bˈɪɡ dˈiːl/' where phrase = 'It''s not a big deal' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dʒˈʌdʒmənt kˈɔːl/' where phrase = 'Judgment call' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dʒˈʌmp ˌɒn ɐ kˈɔːl/' where phrase = 'Jump on a call' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dʒˈʌmp ðə ɡˈʌn/' where phrase = 'Jump the gun' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/dʒˈʌstɪntˈaɪm/' where phrase = 'Just-in-time' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈiːp ɐn ˈaɪ ˈɒn/' where phrase = 'Keep an eye on' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈiːp ɪn tˈʌtʃ/' where phrase = 'Keep in touch' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈiːp mˌiː ɪnðə lˈuːp/' where phrase = 'Keep me in the loop' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈiːp ˈɒpʃənz ˈəʊpən/' where phrase = 'Keep options open' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈiːp juː pˈəʊstɪd/' where phrase = 'Keep you posted' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈiːp jɔː tʃˈɪn ˈʌp/' where phrase = 'Keep your chin up' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈaɪndli/' where phrase = 'Kindly' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˌeɪpˌiːˈaɪ/' where phrase = 'KPI' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈiːd baɪ ɛɡzˈampəl/' where phrase = 'Lead by example' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈiːd tˈaɪm/' where phrase = 'Lead time' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈiːv nˈəʊ stˈəʊn ʌntˈɜːnd/' where phrase = 'Leave no stone unturned' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈɛt mˌiː nˈəʊ ɪf juː hav ˌɛni kwˈɛstʃənz/' where phrase = 'Let me know if you have any questions' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈɛt ðə kˈat ˌaʊtəv ðə bˈaɡ/' where phrase = 'Let the cat out of the bag' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈɛts ɡɹˈab ɐ bˈaɪt/' where phrase = 'Let''s grab a bite' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈɛvəl hˈɛd/' where phrase = 'Level head' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈɛvəl plˈeɪɪŋ fˈiːld/' where phrase = 'Level playing field' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈiːvəɹɪdʒ/' where phrase = 'Leverage' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lədʒˈɪstɪks/' where phrase = 'Logistics' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈʊk fˈɔːwəd tə hˈiəɹɪŋ fɹɒm juː/' where phrase = 'Look forward to hearing from you' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈʊk ˌɪntʊ/' where phrase = 'Look into' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈʊkɪŋ fˈɔːwəd tʊ ɪt/' where phrase = 'Looking forward to it' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈuːp ˈɪn/' where phrase = 'Loop in' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈəʊhˈaŋɪŋ fɹˈuːt/' where phrase = 'Low-hanging fruit' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/lˈəʊbɔːl/' where phrase = 'Lowball' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˌeɪk ɐ kənsˈɛʃən/' where phrase = 'Make a concession' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˌeɪk ɪt ˈʌp tə juː/' where phrase = 'Make it up to you' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˈiːt hˈɑːfweɪ/' where phrase = 'Meet halfway' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˈiːt ɹɪkwˈaɪəmənts/' where phrase = 'Meet requirements' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˈiːt tˈɜːmz/' where phrase = 'Meet terms' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˈɛtɹɪks/' where phrase = 'Metrics' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˌaɪkɹəʊmˈanɪdʒ/' where phrase = 'Micromanage' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˈaɪlstəʊn/' where phrase = 'Milestone' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˈɪs ðə bˈəʊt/' where phrase = 'Miss the boat' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈmuːv ðə ˈɡɔʊlpəʊsts/' where phrase = 'Move the goalposts' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˈuːv ðə nˈiːdəl/' where phrase = 'Move the needle' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/mˈuːvɪŋ fˈɔːwəd/' where phrase = 'Moving forward' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/maɪ bˈad/' where phrase = 'My bad' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/nˈəʊ kan dˈuː/' where phrase = 'No can do' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/nˈəʊ wˈeɪ/' where phrase = 'No way' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/nˈəʊ wˈʌɹiz/' where phrase = 'No worries' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/nˌɒt ɹˈiəlɪ/' where phrase = 'Not really' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌɛnˌɑːɹˈɛn/' where phrase = 'NRN' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈɒf ðə tˈɒp ɒv maɪ hˈɛd/' where phrase = 'Off the top of my head' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌɒn bɪhˈɑːf ɒv/' where phrase = 'On behalf of' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌɒn bˈɔːd/' where phrase = 'On board' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɒnðə bˈɔːl/' where phrase = 'On the ball' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɒnðə sˈeɪm pˈeɪdʒ/' where phrase = 'On the same page' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɒnˈbɔːd/' where phrase = 'Onboard' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈʌns ɪn ɐ blˈuː mˈuːn/' where phrase = 'Once in a blue moon' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈuːəʊ/' where phrase = 'OOO' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈəʊpən tə sədʒˈɛstʃənz/' where phrase = 'Open to suggestions' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈɒptɪks/' where phrase = 'Optics' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈɒptɪmaɪz/' where phrase = 'Optimize' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌaʊtəv ˈɒfɪs/' where phrase = 'Out of office' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌaʊtəv pˈɒkɪt/' where phrase = 'Out of pocket' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌaʊtəv ðə blˈuː/' where phrase = 'Out of the blue' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌaʊtəv ðə lˈuːp/' where phrase = 'Out of the loop' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈaʊtˌsɔː(ɹ).sɪŋ/' where phrase = 'Outsourcing' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈoʊvɚˌhɑl/' where phrase = 'Overhaul' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˈeɪn pˈɔɪnt/' where phrase = 'Pain point' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˈaɹədˌaɪm ʃˈɪft/' where phrase = 'Paradigm shift' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˈɛndɪŋ ɐpɹˈuːvəl/' where phrase = 'Pending approval' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pɜːɹ ˌaʊə lˈast ˈiːmeɪl/' where phrase = 'Per our last email' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pəfˈɔːməns ɹɪvjˈuː/' where phrase = 'Performance review' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pətˈeɪnɪŋ tuː/' where phrase = 'Pertaining to' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/fˈeɪz ˈaʊt/' where phrase = 'Phase out' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˈiːs ɒv kˈeɪk/' where phrase = 'Piece of cake' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˈɪtʃ ˈɪn/' where phrase = 'Pitch in' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈpɪvət/' where phrase = 'Pivot' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/plˈeɪ ɪt baɪ ˈiə/' where phrase = 'Play it by ear' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/plˈiːz biː ɐdvˈaɪzd/' where phrase = 'Please be advised' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/plˈiːz fˈaɪnd ɐtˈatʃt/' where phrase = 'Please find attached' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/plˈiːz fˈaɪnd ɛŋklˈəʊzd/' where phrase = 'Please find enclosed' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/plˈiːz nˈəʊt/' where phrase = 'Please note' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pɹəˈkjʊə.mənt/' where phrase = 'Procurement' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pɹˈɒmpt ɹɪspˈɒns/' where phrase = 'Prompt response' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˈʊl sˈʌmwɒnz lˈɛɡ/' where phrase = 'Pull someone''s leg' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˈʊʃ ðɪ ˈɛnvəlˌəʊp/' where phrase = 'Push the envelope' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˌʊt ɐ pˈɪn ɪn ɪt/' where phrase = 'Put a pin in it' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/pˌʊt hˈɛdz təɡˈɛðə/' where phrase = 'Put heads together' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/kˈɑː/' where phrase = 'QA' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈamp ˈʌp/' where phrase = 'Ramp up' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈiːtʃ ˈaʊt/' where phrase = 'Reach out' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈiːd ðə ɹˈuːm/' where phrase = 'Read the room' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈɛd tˈeɪp/' where phrase = 'Red tape' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˌiːˈɪtəɹˌeɪt/' where phrase = 'Reiterate' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈɛst əʃˈʊəd/' where phrase = 'Rest assured' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈɪŋ ɐ bˈɛl/' where phrase = 'Ring a bell' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈəʊl ˈaʊt/' where phrase = 'Roll out' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌɑːɹˌɛsvˌiːpˈiː/' where phrase = 'RSVP' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈuːl ɒv θˈʌm/' where phrase = 'Rule of thumb' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈʌn bˈaɪ/' where phrase = 'Run by' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈʌn ɪt ˌʌp ðə flˈaɡpəʊl/' where phrase = 'Run it up the flagpole' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/skˈeɪləbəl/' where phrase = 'Scalable' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/skɹʌm/' where phrase = 'Scrum' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈiː ˈaɪ tʊ ˈaɪ/' where phrase = 'See eye to eye' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈiː θɹˈuː/' where phrase = 'See through' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈiː tʊ ɪt ðˈat/' where phrase = 'See to it that' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈiː jɔː pˈɔɪnt/' where phrase = 'See your point' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈɛt ðə bˈɑː hˈaɪ/' where phrase = 'Set the bar high' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ʃˌʊd juː hav ˌɛni kwˈɛstʃənz/' where phrase = 'Should you have any questions' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈaɪnˈɒf/' where phrase = 'Sign-off' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈaɪləʊz/' where phrase = 'Silos' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/smˈɔːl wˈɜːld/' where phrase = 'Small world' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/smˈuːð sˈeɪlɪŋ/' where phrase = 'Smooth sailing' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈɒft skˈɪlz/' where phrase = 'Soft skills' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈaʊndz ɡˈʊd/' where phrase = 'Sounds good' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/sˈaʊndz lˈaɪk ɐ plˈan/' where phrase = 'Sounds like a plan' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/spˈiːk ɒvðə dˈɛvəl/' where phrase = 'Speak of the devil' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/spɪl ðə biːnz/' where phrase = 'Spill the beans' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/spˈɪt ɪt ˈaʊt/' where phrase = 'Spit it out' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/splˈɪt ðə dˈɪfɹəns/' where phrase = 'Split the difference' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/spɹɪnt/' where phrase = 'Sprint' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈsteɪkhoʊldə(ɹ)/' where phrase = 'Stakeholder' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/stˈand fˈɜːm/' where phrase = 'Stand firm' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/stˈandˈʌp/' where phrase = 'Stand-up' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/stˈeɪ ˌɒn tɹˈak/' where phrase = 'Stay on track' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/stˈiːl sˈʌmwɒnz θˈʌndə/' where phrase = 'Steal someone''s thunder' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/stˈiə klˈiəɹ ɒv/' where phrase = 'Steer clear of' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/stˈɪk tə ðə pˈɔɪnt/' where phrase = 'Stick to the point' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/stɹˈiːmlaɪn/' where phrase = 'Streamline' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/səplˈaɪ tʃˈeɪn/' where phrase = 'Supply chain' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/swˈiːtən ðə dˈiːl/' where phrase = 'Sweeten the deal' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈsɪnədʒi/' where phrase = 'Synergy' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪbəl ðə dɪskˈʌʃən/' where phrase = 'Table the discussion' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ɐ bˈaksiːt/' where phrase = 'Take a backseat' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ɐ hˈɪt/' where phrase = 'Take a hit' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ɐ ɹˈeɪn tʃˈɛk/' where phrase = 'Take a rain check' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ˌɪntʊ ɐkˈaʊnt/' where phrase = 'Take into account' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ɪt ˈiːzi/' where phrase = 'Take it easy' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ɪt ˈɒflaɪn/' where phrase = 'Take it offline' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ɪt ɔː lˈiːv ɪt/' where phrase = 'Take it or leave it' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ˈəʊnəʃˌɪp/' where phrase = 'Take ownership' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk ðə lˈiːd/' where phrase = 'Take the lead' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈeɪk wɪð ɐ ɡɹˈeɪn ɒv sˈɒlt/' where phrase = 'Take with a grain of salt' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈɔːk sˈʌmwɒn ˌɪntʊ/' where phrase = 'Talk someone into' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˌiːbˌiːdˈiː slˈaʃ tˌiːbˌiːˈeɪ/' where phrase = 'TBD / TBA' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈɜːmz and kəndˈɪʃənz/' where phrase = 'Terms and conditions' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/θˈaŋk juː fɔː jɔː kəʊˈɒpəɹˈeɪʃən/' where phrase = 'Thank you for your cooperation' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ðat mˌeɪks sˈɛns/' where phrase = 'That makes sense' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ðats ɐ ɡˈʊd wˌɒn/' where phrase = 'That''s a good one' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ðats ɐ ʃˈeɪm/' where phrase = 'That''s a shame' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ðats hˌaʊ ɪt ɡˈəʊz/' where phrase = 'That''s how it goes' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/θˈɪŋk aʊtsˈaɪd ðə bˈɒks/' where phrase = 'Think outside the box' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/θɹuː θˈɪk and θˈɪn/' where phrase = 'Through thick and thin' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/θɹˈəʊ ɪnðə tˈaʊəl/' where phrase = 'Throw in the towel' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈaɪ ˌʌp lˈuːs ˈɛndz/' where phrase = 'Tie up loose ends' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈaɪtən bˈɛlts/' where phrase = 'Tighten belts' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈaɪm flˈaɪz/' where phrase = 'Time flies' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tə hˈuːm ɪt mˈeɪ kənsˈɜːn/' where phrase = 'To whom it may concern' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈʌtʃ and ɡˈəʊ/' where phrase = 'Touch and go' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈʌtʃ bˈeɪs/' where phrase = 'Touch base' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈʌtʃ əpˌɒn/' where phrase = 'Touch upon' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈʌtʃpɔɪnt/' where phrase = 'Touchpoint' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈtɹæk.ʃən/' where phrase = 'Traction' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/tˈɜːnɐɹˌaʊnd tˈaɪm/' where phrase = 'Turnaround time' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/twˈɪst maɪ ˈɑːm/' where phrase = 'Twist my arm' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈʌndə ðə ˈwɛðə/' where phrase = 'Under the weather' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ʌnfɔːsˈiːn sˈɜːkəmstˌansɪz/' where phrase = 'Unforeseen circumstances' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ʌnˈpæk/' where phrase = 'Unpack' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌʌp ɪnðɪ ˈeə/' where phrase = 'Up in the air' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌʌp ðɪ ˈantiː/' where phrase = 'Up the ante' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌʌp tə spˈiːd/' where phrase = 'Up to speed' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˌʌpə hˈand/' where phrase = 'Upper hand' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/vˈaljuːˈad/' where phrase = 'Value-add' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/vˈaljuːd kˈʌstəmə/' where phrase = 'Valued customer' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈɔːk ɐwˈeɪ/' where phrase = 'Walk away' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈɔːk mˌiː θɹˈuː/' where phrase = 'Walk me through' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈɔːm ɹɪɡˈɑːdz/' where phrase = 'Warm regards' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈɛðə ðə stˈɔːm/' where phrase = 'Weather the storm' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈʍiːlˌhaʊs/' where phrase = 'Wheelhouse' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈaɪld ɡˈuːs tʃˈeɪs/' where phrase = 'Wild goose chase' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈɪnwˈɪn sˌɪtʃuːˈeɪʃən/' where phrase = 'Win-win situation' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wɪð ɹˈɛfɹəns tuː/' where phrase = 'With reference to' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈɜːklˈaɪf bˈaləns/' where phrase = 'Work-life balance' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ˈwɜːkfləʊ/' where phrase = 'Workflow' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wˈɜːθ ɐ ʃˈɒt/' where phrase = 'Worth a shot' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/wɜː(ɹ)θˈwaɪl/' where phrase = 'Worthwhile' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/ɹˈap jɔː hˈɛd ɐɹˈaʊnd/' where phrase = 'Wrap your head around' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/juː kan sˈeɪ ðat ɐɡˈɛn/' where phrase = 'You can say that again' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/jɔː tˈɛlɪŋ mˌiː/' where phrase = 'You''re telling me' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/juːv ɡɒt təbi kˈɪdɪŋ mˌiː/' where phrase = 'You''ve got to be kidding me' and coalesce(nullif(trim(ipa), ''), null) is null;
update public.phrases set ipa = '/zˈiəɹəʊsˈʌm/' where phrase = 'Zero-sum' and coalesce(nullif(trim(ipa), ''), null) is null;
